[shortcuts]
b = "Brave (new window)"
g = "Ghostty (new window)"
d = "Sleep"
l = "Lock screen"
s = "Sublime (new window)"
v = "Screensaver"
p = "Toggle pin"

[service]
esc = "Reload config"
r = "Reset workspace layout"
f = "Toggle float/tile"
backspace = "Close all windows but current"
